import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  root: 'app',
  // Brand assets live at the repository root, not inside the app source, so
  // they can be regenerated by scripts/generate-brand-assets.mjs.
  publicDir: '../public',
  plugins: [react()],
  build: {
    outDir: '../dist/client',
    emptyOutDir: true,
  },
})
