import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// The social card has to carry an absolute URL: the crawlers fetch og:image
// without a base, so a relative path produces no preview rather than a broken
// one. The origin differs per environment and is only known at build time, so
// the workflows pass it in. The fallback is production, not a placeholder: a
// build that forgets the variable should still ship a card that resolves.
//
// When a real domain lands (#60) this default and the three workflow values are
// the only things that change.
const SOCIAL_ORIGIN = (process.env.VITE_PUBLIC_ORIGIN || 'https://nepscene.bhattarai-shiva.workers.dev').replace(
  /\/+$/,
  '',
)

export default defineConfig({
  root: 'app',
  // Brand assets live at the repository root, not inside the app source, so
  // they can be regenerated by scripts/generate-brand-assets.mjs.
  publicDir: '../public',
  plugins: [
    react(),
    {
      name: 'nepscene-social-origin',
      transformIndexHtml: (html: string) => html.replaceAll('%SOCIAL_ORIGIN%', SOCIAL_ORIGIN),
    },
  ],
  build: {
    outDir: '../dist/client',
    emptyOutDir: true,
  },
})
