#!/usr/bin/env node
/**
 * Volume seed (#26) — generates a catalogue large enough to find the things a
 * 14-row demo seed cannot: pagination that degrades, a query plan that stops
 * using an index, a response that grows past its budget.
 *
 * It writes one SQL file of batched multi-row INSERTs and hands it to wrangler,
 * because 10,000 round trips would take longer than the whole budget.
 *
 * Usage:
 *   node scripts/seed-volume.mjs --count 10000                 # local
 *   node scripts/seed-volume.mjs --count 10000 --env preview   # remote
 */
import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const args = process.argv.slice(2)
const arg = (name, fallback) => {
  const i = args.indexOf(`--${name}`)
  return i === -1 ? fallback : args[i + 1]
}

const COUNT = Number(arg('count', 10000))
const ENV = arg('env', null)
// 500 rows in one INSERT trips SQLITE_TOOBIG — SQLite caps statement length,
// and wrangler sends the file statement by statement.
const BATCH = 100

if (!Number.isInteger(COUNT) || COUNT < 1 || COUNT > 200_000) {
  console.error('--count must be between 1 and 200000')
  process.exit(1)
}

// Deterministic: the same --count always produces the same catalogue, so a
// measurement taken today can be compared with one taken next month.
let seed = 20260902
const random = () => {
  seed = (seed * 1103515245 + 12345) & 0x7fffffff
  return seed / 0x7fffffff
}
const pick = (list) => list[Math.floor(random() * list.length)]

const CATEGORIES = ['cat_concert','cat_festival','cat_sports','cat_comedy','cat_food',
                    'cat_nightlife','cat_arts','cat_community','cat_workshop','cat_film',
                    'cat_market','cat_religious']
const TYPES = ['ticketed_internal','ticketed_external','free','announcement']
const SOURCES = ['organizer','submission','import','editorial']
const WORDS = ['Himalayan','Valley','Monsoon','Lakeside','Thamel','Newari','Kirtipur','Rato',
               'Machhindranath','Jazz','Indie','Folk','Sunrise','Annapurna','Bagmati','Patan',
               'Dawn','Midnight','Rooftop','Courtyard','Terrace','Riverside']
const KINDS = ['Session','Night','Festival','Market','Walk','Screening','Jam','Workshop',
               'Gathering','Showcase','Run','Exhibition']
// Cities carry real coordinates so distance filtering is exercised, not faked.
const CITIES = [
  ['Kathmandu', 27.7172, 85.3240], ['Pokhara', 28.2096, 83.9856],
  ['Lalitpur', 27.6644, 85.3188],  ['Bhaktapur', 27.6710, 85.4298],
  ['Biratnagar', 26.4525, 87.2718],['Birgunj', 27.0104, 84.8770],
  ['Dharan', 26.8065, 87.2846],    ['Butwal', 27.7006, 83.4484],
  ['Nepalgunj', 28.0500, 81.6167], ['Janakpur', 26.7288, 85.9266],
]

const iso = (offsetDays, hour) => {
  const d = new Date(Date.now() + offsetDays * 86_400_000)
  d.setUTCHours(hour, 0, 0, 0)
  return d.toISOString()
}
const esc = (v) => (v === null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)

const started = Date.now()
const lines = [
  '-- Generated by scripts/seed-volume.mjs — do not edit, regenerate.',
  "DELETE FROM listing_categories WHERE listing_id LIKE 'vol_%';",
  "DELETE FROM listings WHERE id LIKE 'vol_%';",
  "DELETE FROM venues WHERE id LIKE 'vol_%';",
]

// One venue per city, so listings share venues the way real ones do.
const venueValues = CITIES.map(([city, lat, lng], i) => {
  const id = `vol_ven_${i}`
  return `(${esc(id)}, ${esc(`volume-venue-${i}`)}, ${esc(`${city} Volume Venue`)}, ${esc(city)}, ` +
         `${esc(city)}, ${esc('Bagmati')}, ${lat}, ${lng}, ${esc(iso(0, 0))}, ${esc(iso(0, 0))})`
})
lines.push(
  'INSERT INTO venues (id, slug, name, area, city, province, latitude, longitude, created_at, updated_at) VALUES',
  venueValues.join(',\n') + ';',
)

const now = iso(0, 0)
for (let start = 0; start < COUNT; start += BATCH) {
  const rows = []
  for (let n = start; n < Math.min(start + BATCH, COUNT); n++) {
    const id = `vol_${n}`
    // A quarter of the catalogue is in the past, so the upcoming-by-default
    // filter is doing real work at volume rather than matching everything.
    const offset = n % 4 === 0 ? -Math.floor(random() * 200) - 1 : Math.floor(random() * 400) + 1
    const startsAt = iso(offset, 6 + Math.floor(random() * 14))
    const endsAt = random() < 0.4 ? iso(offset, 22) : null
    const title = `${pick(WORDS)} ${pick(WORDS)} ${pick(KINDS)} ${n}`
    const type = pick(TYPES)
    const price = type.startsWith('ticketed') ? Math.floor(random() * 40) * 5000 + 5000 : null

    rows.push(
      `(${esc(id)}, ${esc(`volume-listing-${n}`)}, ${esc(title)}, ${esc(`${title} — generated for volume testing.`)}, ` +
      `${esc(type)}, ${esc(pick(SOURCES))}, 'published', NULL, ${esc(`vol_ven_${n % CITIES.length}`)}, ` +
      `${esc(startsAt)}, ${endsAt ? esc(endsAt) : 'NULL'}, ${random() < 0.02 ? 1 : 0}, ` +
      `${price === null ? 'NULL' : price}, ${price === null ? 'NULL' : esc('external')}, ` +
      // A price with nowhere to buy is not an offer. verify-catalogue.mjs
      // flags it, and generated data has to pass the same checks as real data.
      `${price === null ? 'NULL' : esc(`https://example.np/tickets/${n}`)}, ` +
      `${esc(startsAt)}, ${esc(now)}, ${esc(now)})`,
    )
  }
  lines.push(
    'INSERT INTO listings (id, slug, title, summary, listing_type, source, status, organization_id,' +
    ' venue_id, starts_at, ends_at, is_featured, offer_price_from_paisa, offer_provider,' +
    ' offer_url, published_at, created_at, updated_at) VALUES',
    rows.join(',\n') + ';',
  )

  const categoryRows = []
  for (let n = start; n < Math.min(start + BATCH, COUNT); n++) {
    categoryRows.push(`(${esc(`vol_${n}`)}, ${esc(pick(CATEGORIES))}, 1)`)
  }
  lines.push(
    'INSERT OR IGNORE INTO listing_categories (listing_id, category_id, is_primary) VALUES',
    categoryRows.join(',\n') + ';',
  )
}

const file = join(mkdtempSync(join(tmpdir(), 'nepscene-volume-')), 'volume.sql')
writeFileSync(file, lines.join('\n'))
console.log(`Generated ${COUNT} listings across ${CITIES.length} venues in ${Date.now() - started}ms`)
console.log(`  ${file}`)

const wranglerArgs = ['wrangler', 'd1', 'execute', ENV ? 'DB' : 'nepscene-local']
if (ENV) wranglerArgs.push('--env', ENV, '--remote')
else wranglerArgs.push('--local')
wranglerArgs.push(`--file=${file}`)

console.log(`Applying with: npx ${wranglerArgs.join(' ')}`)
execFileSync('npx', wranglerArgs, { stdio: 'inherit' })
console.log(`Done in ${((Date.now() - started) / 1000).toFixed(1)}s`)
